---
title: "czs_s1_preprocess"
output: html_document
---

```{r,include=FALSE}
detachAllPackages <- function() {

  basic.packages <- c("package:stats","package:graphics","package:grDevices","package:utils","package:datasets","package:methods","package:base")

  package.list <- search()[ifelse(unlist(gregexpr("package:",search()))==1,TRUE,FALSE)]

  package.list <- setdiff(package.list,basic.packages)

  if (length(package.list)>0)  for (package in package.list) detach(package, character.only=TRUE)

}

detachAllPackages()
```

```{r setup, include=FALSE}
library(tidyverse)

repo_url <- "https://raw.githubusercontent.com/deanbaltiansky/class-zero-sum-beliefs/main/study-1/data/"

df_deid <- readr::read_csv(paste0(repo_url,"df_raw_deid.csv"), show_col_types = FALSE)
```

# Study 1

remove ineligible participants

```{r}
#keep only those who finished
df_s1 <- df_deid %>% 
  filter(Finished == 1) %>% 
  filter(Progress == 100)
```

Put NA's where necessary

```{r}
df_s1 <- df_s1 %>% 
  mutate(income = ifelse(income == "Prefer not to answer",NA,income))
```

define income and edu as factors

```{r}
df_s1 <- df_s1 %>% 
  mutate(income = factor(income,c("$0-$20,000",
                                  "$20,001-$40,000",
                                  "$40,001-$60,000",
                                  "$60,001-$80,000",
                                  "$80,001-$100,000",
                                  "$100,001-$120,000",
                                  "$120,001-$140,000",
                                  "$140,001-$160,000",
                                  "$160,001-$180,000",
                                  "$180,001-$200,000",
                                  "Over $200,000")),
         edu = factor(edu,c("noHS",
                            "GED",
                            "2yearColl",
                            "4yearColl",
                            "MA",
                            "PHD")))
```

fix race

```{r}
df_s1 <- df_s1 %>% 
  mutate_at(vars(race_1:race_8),function(x){as.character(x)}) %>% 
  mutate_at(vars(race_1:race_8),function(x){replace_na(x,"")}) %>% 
  mutate(race_num_1 = ifelse(race_1 != "",1,0),
         race_num_2 = ifelse(race_2 != "",1,0),
         race_num_3 = ifelse(race_3 != "",1,0),
         race_num_4 = ifelse(race_4 != "",1,0),
         race_num_5 = ifelse(race_5 != "",1,0),
         race_num_6 = ifelse(race_6 != "",1,0),
         race_num_7 = ifelse(race_7 != "",1,0),
         race_num_8 = ifelse(race_8 != "",1,0),
         race_num = race_num_1 + race_num_2 + race_num_3 + race_num_4 + race_num_5 + race_num_6 + race_num_7 + race_num_8,
         race = ifelse(race_num > 1,"multiracial",paste0(race_1,race_2,race_3,race_4,race_5,race_6,race_7,race_8)),
         race = ifelse(race == "",NA,race))
```

reverse-scores

```{r}
df_s1 <- df_s1 %>% 
  mutate(zs_class_3R = 8 - zs_class_3,
         SDO_3R = 8 - SDO_3,
         SDO_4R = 8 - SDO_4,
         SDO_7R = 8 - SDO_7,
         SDO_8R = 8 - SDO_8,
         zsm_5R = 8 - zsm_5,
         zsm_7R = 8 - zsm_7)
```

create mean scores

```{r}
df_s1 <- df_s1 %>% 
  rowwise() %>% 
  mutate(zs_class = mean(c(zs_class_1,
                           zs_class_2,
                           zs_class_3R),na.rm = T),
         SDO = mean(c(SDO_1,
                      SDO_2,
                      SDO_3R,
                      SDO_4R,
                      SDO_5,
                      SDO_6,
                      SDO_7R,
                      SDO_8R),na.rm = T),
         zsm = mean(c(zsm_1,
                      zsm_2,
                      zsm_3,
                      zsm_4,
                      zsm_5R,
                      zsm_6,
                      zsm_7R),na.rm = T),
         soli = mean(c(soli_1,
                       soli_2,
                       soli_3,
                       soli_4,
                       soli_5,
                       soli_6),na.rm = T)) %>% 
  ungroup() %>% 
  mutate(impact = impact_groups_1 + impact_groups_2)
```

rename some vars

```{r}
df_s1 <- df_s1 %>% 
  rename(ideo_con = ideo_1,
         ideo_lib = ideo_2,
         ideo_demsoc = ideo_3,
         ideo_lbrtn = ideo_4,
         ideo_prog = ideo_5,
         impact_wc = impact_groups_1,
         impact_uc = impact_groups_2)
```

attention check

```{r}
df_s1 <- df_s1 %>% 
  mutate(att_1 = ifelse(check_1 == 5,1,0))
```

order of blocks

```{r}
df_s1 <- df_s1 %>% 
  mutate(blockorder = ifelse(FL_64_DO_FL_65 == 1,"wordlviews_first","policy_first"),
         soli_first = ifelse(FL_65_DO_ClassSolidarity == 1,1,0))
```

take only necessary variables

```{r}
df_s1 <- df_s1 %>% 
  dplyr::select(PID,
                zs_class,
                SDO,
                zsm,
                lnktfate,
                soli,
                support,
                impact,
                impact_uc,
                impact_wc,
                zs_class_1,
                zs_class_2,
                zs_class_3R,
                SDO_1,
                SDO_2,
                SDO_3R,
                SDO_4R,
                SDO_5,
                SDO_6,
                SDO_7R,
                SDO_8R,
                zsm_1,
                zsm_2,
                zsm_3,
                zsm_4,
                zsm_5R,
                zsm_6,
                zsm_7R,
                soli_1:soli_6,
                ideo_con:ideo_prog,
                party_id:vote_2024,
                policy,
                blockorder,
                soli_first,
                att_1,
                age,
                gender,
                race,
                edu,
                income,
                class,
                feedback)
```

write csv

```{r}
write.csv(df_s1,"~/Google Drive/My Drive/Class-Based Zero-Sum/for github/class-zero-sum-beliefs/study-1/data/df_czs.csv",row.names = F)

write.csv(df_s1 %>% filter(att_1 == 1),"~/Google Drive/My Drive/Class-Based Zero-Sum/for github/class-zero-sum-beliefs/study-1/data/df_czs_elg.csv",row.names = F)
```

